-- CreateTable
CREATE TABLE "Bot" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "environment" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT false,
    "startDate" TIMESTAMP(3) NOT NULL,
    "operationMode" TEXT NOT NULL,
    "operationTime" JSONB,
    "primaryIndicator" TEXT NOT NULL,
    "secondaryIndicator" TEXT,
    "confirmationIndicator" TEXT,
    "entryType" TEXT NOT NULL,
    "entryCondition" TEXT NOT NULL,
    "entryValue" DOUBLE PRECISION,
    "exitType" TEXT NOT NULL,
    "exitCondition" TEXT NOT NULL,
    "exitValue" DOUBLE PRECISION,
    "positionSizingType" TEXT NOT NULL,
    "positionSizingValue" DOUBLE PRECISION NOT NULL,
    "maxPosition" DOUBLE PRECISION NOT NULL,
    "partialExitsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "partialExitsLevels" JSONB,
    "stopLossEnabled" BOOLEAN NOT NULL DEFAULT false,
    "stopLossType" TEXT NOT NULL,
    "stopLossValue" DOUBLE PRECISION,
    "takeProfitEnabled" BOOLEAN NOT NULL DEFAULT false,
    "takeProfitType" TEXT NOT NULL,
    "takeProfitValue" DOUBLE PRECISION,
    "maxDailyLoss" DOUBLE PRECISION NOT NULL,
    "maxDrawdown" DOUBLE PRECISION NOT NULL,
    "maxOpenPositions" INTEGER NOT NULL,
    "timeFilterEnabled" BOOLEAN NOT NULL DEFAULT false,
    "timeFilterStart" TEXT,
    "timeFilterEnd" TEXT,
    "newsFilterEnabled" BOOLEAN NOT NULL DEFAULT false,
    "avoidNewsMinutes" INTEGER NOT NULL DEFAULT 30,
    "correlationFilterEnabled" BOOLEAN NOT NULL DEFAULT false,
    "maxCorrelation" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    "totalTrades" INTEGER NOT NULL DEFAULT 0,
    "winningTrades" INTEGER NOT NULL DEFAULT 0,
    "losingTrades" INTEGER NOT NULL DEFAULT 0,
    "winRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalProfit" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalLoss" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "netProfit" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "sharpeRatio" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "profitFactor" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "averageWin" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "averageLoss" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "largestWin" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "largestLoss" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "consecutiveWins" INTEGER NOT NULL DEFAULT 0,
    "consecutiveLosses" INTEGER NOT NULL DEFAULT 0,
    "currentStreak" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Bot_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Trade" ADD CONSTRAINT "Trade_botId_fkey" FOREIGN KEY ("botId") REFERENCES "Bot"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bot" ADD CONSTRAINT "Bot_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
